language: rust

matrix:
  include:
  - name: "stable"
    rust: stable
    sudo: required
    before_script: rustup component add clippy-preview
    script:
      - cargo test --all-features
      - cargo clippy --all-features
    env: RUSTFLAGS="-C link-dead-code -D warnings"
    addons:
      apt:
        packages:
          - libssl-dev

    cache: cargo

    before_cache: |
      if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
        cargo install cargo-tarpaulin -f
      fi

    after_success: |
      if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
        cargo tarpaulin --out Xml
        bash <(curl -s https://codecov.io/bash)
      fi

  - name: "beta test"
    rust: beta
    script: cargo test --all-features

  - name: "beta build"
    rust: beta
    script: cargo build --all-features
    env: RUSTFLAGS="-D warnings"

  - name: "beta clippy"
    rust: beta
    before_script: rustup component add clippy-preview
    script: cargo clippy --all-features
    env: RUSTFLAGS="-D warnings"

  - name: "nightly test"
    rust: nightly
    script: cargo test --all-features

  - name: "nightly build"
    rust: nightly
    script: cargo build --all-features
    env: RUSTFLAGS="-D warnings"

  - name: "nightly clippy"
    rust: nightly
    before_script: rustup component add clippy-preview
    script: cargo clippy --all-features
    env: RUSTFLAGS="-D warnings"

  allow_failures:
    - rust: nightly
    - name: "beta build"
    - name: "beta clippy"
